'use strict';function t(f,a,b,d){f.v.ic(f.Wa,a,b,d,void 0)}function B(f,a,b,d){f.v.pa?t(f,a,b,d):f.v.bf()._OnMessageFromDOM({type:"event",component:f.Wa,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function D(f,a,b){f.v.B(f.Wa,a,b)}function E(f,a){for(const [b,d]of a)D(f,b,d)}function F(f){f.Mb||(f.v.Ne(f.Wd),f.Mb=!0)}window.Qa=class{constructor(f,a){this.v=f;this.Wa=a;this.Mb=!1;this.Wd=()=>this.Ca()}$c(){}Ca(){}};function G(f){-1!==f.Na&&(self.clearTimeout(f.Na),f.Na=-1)}
window.Ee=class{constructor(f,a){this.Hc=f;this.og=a;this.Na=-1;this.Nb=-Infinity;this.Xd=()=>{this.Na=-1;this.Nb=Date.now();this.ab=!0;this.Hc();this.ab=!1};this.Gd=this.ab=!1}c(){G(this);this.Xd=this.Hc=null}};"use strict";function I(f,a){const b=a.elementId,d=f.dd(b,a);f.Y.set(b,d);a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{J(f,"elem-focused",b)});d.addEventListener("blur",()=>{J(f,"elem-blurred",b)});f.Hb&&document.body.appendChild(d)}
function K(f,a){D(f,"get-element",b=>{const d=f.Y.get(b.elementId);return a(d,b)})}function J(f,a,b){var d;d||(d={});d.elementId=b;t(f,a,d)}
window.qe=class extends self.Qa{constructor(f,a){super(f,a);this.Y=new Map;this.Hb=!0;E(this,[["create",b=>I(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Hb&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Hb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Hb){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.oc(d,b)}}],["focus",b=>this.Cc(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);K(this,b=>b)}dd(){throw Error("required override");}oc(){throw Error("required override");}Cc(f){var a=this.Y.get(f.elementId);f.focus?a.focus():a.blur()}};
"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function a(v){if(v.yg){const h=document.createElement("script");h.async=!1;h.textContent=v.Bg;document.head.appendChild(h)}else return new Promise((h,k)=>{const c=document.createElement("script");c.onload=h;c.onerror=k;c.async=!1;c.src=v;document.head.appendChild(c)})}let b=new Audio;const d={"audio/webm; codecs=opus":!!b.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!b.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!b.canPlayType("audio/webm; codecs=vorbis"),
"audio/ogg; codecs=vorbis":!!b.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!b.canPlayType("audio/mp4"),"audio/mpeg":!!b.canPlayType("audio/mpeg")};b=null;async function g(v){v=await n(v);return(new TextDecoder("utf-8")).decode(v)}function n(v){return new Promise((h,k)=>{const c=new FileReader;c.onload=e=>h(e.target.result);c.onerror=e=>k(e);c.readAsArrayBuffer(v)})}const q=[];let u=0;window.RealFile=window.File;const x=[],A=new Map,w=new Map;let y=0;const C=[];self.Ng=function(v){if("function"!==
typeof v)throw Error("runOnStartup called without a function");C.push(v)};const z=new Set(["cordova","playable-ad","instant-games"]);window.Ba=class v{constructor(h){this.pa=h.Dg;this.na=null;this.K="";this.Vb=h.Ag;this.pb={};this.ma=this.Ga=this.ob=null;this.Kb=[];this.cb=this.J=this.La=null;this.Ka=-1;this.tg=()=>this.Af();this.Ja=[];this.C=h.Yd;!this.pa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||(this.pa=!1);z.has(this.C)&&this.pa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.pa=!1);this.Pb=this.ha=null;"html5"!==this.C&&"playable-ad"!==this.C||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",k=>this.jf(k));this.B("runtime","create-job-worker",()=>this.kf());"cordova"===this.C?document.addEventListener("deviceready",()=>this.td(h)):this.td(h)}c(){this.pc();this.na&&(this.na=
this.na.onmessage=null);this.ob&&(this.ob.terminate(),this.ob=null);this.Ga&&(this.Ga.c(),this.Ga=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}hd(){return f&&"cordova"===this.C}tb(){return f&&z.has(this.C)||navigator.standalone}async td(h){"preview"===this.C&&(this.ma=document.createElement("div"),this.ma.className="previewLoadingMessage",this.ma.textContent=h.Lg,document.body.appendChild(this.ma));if("playable-ad"===this.C){this.ha=self.c3_base64files;this.Pb={};await this.Se();
for(let c=0,e=h.Oa.length;c<e;++c){var k=h.Oa[c].toLowerCase();this.Pb.hasOwnProperty(k)?h.Oa[c]={yg:!0,Bg:this.Pb[k]}:this.ha.hasOwnProperty(k)&&(h.Oa[c]=URL.createObjectURL(this.ha[k]))}}h.vg?this.K=h.vg:(k=location.origin,this.K=("null"===k?"file:///":k)+location.pathname,k=this.K.lastIndexOf("/"),-1!==k&&(this.K=this.K.substr(0,k+1)));if(h.Fg)for(const [c,e]of Object.entries(h.Fg))this.pb[c]=URL.createObjectURL(e);k=new MessageChannel;this.na=k.port1;this.na.onmessage=c=>this._OnMessageFromRuntime(c.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.wf(c));this.cb=new self.Ae(this);await L(this.cb);this.jd();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.pa?await this.df(h,k.port2):await this.cf(h,k.port2)}sc(h){return this.pb.hasOwnProperty(h)?this.pb[h]:h.endsWith("/workermain.js")&&this.pb.hasOwnProperty("workermain.js")?this.pb["workermain.js"]:"playable-ad"===this.C&&
this.ha.hasOwnProperty(h.toLowerCase())?URL.createObjectURL(this.ha[h.toLowerCase()]):h}async ac(h,k,c){if(h.startsWith("blob:"))return new Worker(h,c);if(this.hd()&&"file:"===location.protocol)return h=await this.$b(this.Vb+h),new Worker(URL.createObjectURL(new Blob([h],{type:"application/javascript"})),c);h=new URL(h,k);if(location.origin!==h.origin){h=await fetch(h);if(!h.ok)throw Error("failed to fetch worker script");h=await h.blob();return new Worker(URL.createObjectURL(h),c)}return new Worker(h,
c)}ua(){return Math.max(window.innerWidth,1)}ta(){return Math.max(window.innerHeight,1)}jd(){if(this.tb()){const h=document.documentElement.style,k=document.body.style,c=window.innerWidth<window.innerHeight,e=c?window.screen.width:window.screen.height;k.height=h.height=(c?window.screen.height:window.screen.width)+"px";k.width=h.width=e+"px"}}sd(h){var k=this.cb;return{baseUrl:this.K,windowInnerWidth:this.ua(),windowInnerHeight:this.ta(),devicePixelRatio:window.devicePixelRatio,isFullscreen:v.hc(),
projectData:h.Mg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:h.Yd,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Kg,jobScheduler:{inputPort:k.Nc,outputPort:k.Uc,maxNumWorkers:k.qg},supportedAudioFormats:d,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Vb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Vb+"opus.wasm.wasm",isiOSCordova:this.hd(),isiOSWebView:this.tb(),isFBInstantAvailable:"undefined"!==
typeof self.FBInstant}}async df(h,k){var c=this.sc(h.Eg);this.ob=await this.ac(c,this.K,{name:"Runtime"});this.J=document.createElement("canvas");this.J.style.display="none";c=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;this.ob.postMessage(Object.assign(this.sd(h),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:c,workerDependencyScripts:h.Zc||[],engineScripts:h.Oa,projectScripts:window.Jg,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,c,...M(this.cb)]);this.Kb=x.map(e=>new e(this));this.rd();self.c3_callFunction=(e,l)=>this.La.ef(e,l);"preview"===this.C&&(self.goToLastErrorScript=()=>this.ic("runtime","go-to-last-error-script"))}async cf(h,k){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;this.Kb=x.map(e=>new e(this));this.rd();const c=h.Oa.map(e=>"string"===typeof e?(new URL(e,this.K)).toString():e);Array.isArray(h.Zc)&&c.unshift(...h.Zc);await Promise.all(c.map(e=>
a(e)));if(h.Zd&&0<h.Zd.length){const e=self.C3_ProjectScriptsStatus;try{if(await Promise.all(h.Zd.map(l=>a(l[1]))),Object.values(e).some(l=>!l)){self.setTimeout(()=>this.Bd(e),100);return}}catch(l){console.error("[Preview] Error loading project scripts: ",l);self.setTimeout(()=>this.Bd(e),100);return}}"preview"===this.C&&"object"!==typeof self.Gg.Hg?(this.Db(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(h=Object.assign(this.sd(h),{isInWorker:!1,messagePort:k,canvas:this.J,runOnStartupFunctions:C}),this.vd(),this.Ga=self.C3_CreateRuntime(h),await self.C3_InitRuntime(this.Ga,h))}Bd(h){this.Db();h=`Failed to load project script '${Object.entries(h).filter(k=>!k[1]).map(k=>k[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+h);alert(h)}vd(){this.Db()}Db(){this.ma&&(this.ma.parentElement.removeChild(this.ma),this.ma=null)}async kf(){const h=await N(this.cb);return{outputPort:h,
transferables:[h]}}bf(){if(this.pa)throw Error("not available in worker mode");return this.Ga}ic(h,k,c,e,l){this.na.postMessage({type:"event",component:h,handler:k,dispatchOpts:e||null,data:c,responseId:null},l)}kd(h,k,c,e,l){const m=y++,p=new Promise((r,H)=>{w.set(m,{resolve:r,reject:H})});this.na.postMessage({type:"event",component:h,handler:k,dispatchOpts:e||null,data:c,responseId:m},l);return p}["_OnMessageFromRuntime"](h){const k=h.type;if("event"===k)return this.qf(h);if("result"===k)this.Df(h);
else if("runtime-ready"===k)this.Ef();else if("alert-error"===k)this.Db(),alert(h.message);else if("creating-runtime"===k)this.vd();else throw Error(`unknown message '${k}'`);}qf(h){const k=h.component,c=h.handler,e=h.data,l=h.responseId;if(h=A.get(k))if(h=h.get(c)){var m=null;try{m=h(e)}catch(p){console.error(`Exception in '${k}' handler '${c}':`,p);null!==l&&this.Bb(l,!1,""+p);return}if(null===l)return m;m&&m.then?m.then(p=>this.Bb(l,!0,p)).catch(p=>{console.error(`Rejection from '${k}' handler '${c}':`,
p);this.Bb(l,!1,""+p)}):this.Bb(l,!0,m)}else console.warn(`[DOM] No handler '${c}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Bb(h,k,c){let e;c&&c.transferables&&(e=c.transferables);this.na.postMessage({type:"result",responseId:h,isOk:k,result:c},e)}Df(h){const k=h.responseId,c=h.isOk;h=h.result;const e=w.get(k);c?e.resolve(h):e.reject(h);w.delete(k)}B(h,k,c){let e=A.get(h);e||(e=new Map,A.set(h,e));if(e.has(k))throw Error(`[DOM] Component '${h}' already has handler '${k}'`);
e.set(k,c)}static Pa(h){if(x.includes(h))throw Error("DOM handler already added");x.push(h)}rd(){for(const h of this.Kb)if("runtime"===h.Wa){this.La=h;return}throw Error("cannot find runtime DOM handler");}wf(h){this.ic("debugger","message",h)}Ef(){for(const h of this.Kb)h.$c()}static hc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ne(h){this.Ja.push(h);this.Fc()}Pf(h){h=this.Ja.indexOf(h);if(-1===h)throw Error("invalid callback");this.Ja.splice(h,
1);this.Ja.length||this.pc()}Fc(){-1===this.Ka&&this.Ja.length&&(this.Ka=requestAnimationFrame(this.tg))}pc(){-1!==this.Ka&&(cancelAnimationFrame(this.Ka),this.Ka=-1)}Af(){this.Ka=-1;for(const h of this.Ja)h();this.Fc()}sa(h){this.La.sa(h)}Aa(h){this.La.Aa(h)}Ec(){this.La.Ec()}wb(h){this.La.wb(h)}ye(){return!!d["audio/webm; codecs=opus"]}async mg(h){h=await this.kd("runtime","opus-decode",{arrayBuffer:h},null,[h]);return new Float32Array(h)}xe(h){return/^(?:[a-z]+:)?\/\//.test(h)||"data:"===h.substr(0,
5)||"blob:"===h.substr(0,5)}ze(h){return!this.xe(h)}async jf(h){const k=h.filename;switch(h.as){case "text":return await this.pe(k);case "buffer":return await this.$b(k);default:throw Error("unsupported type");}}cd(h){const k=window.cordova.file.applicationDirectory+"www/"+h.toLowerCase();return new Promise((c,e)=>{window.resolveLocalFileSystemURL(k,l=>{l.file(c,e)},e)})}async pe(h){h=await this.cd(h);return await g(h)}qc(){if(q.length&&!(8<=u)){u++;var h=q.shift();this.Te(h.filename,h.Cg,h.xg)}}$b(h){return new Promise((k,
c)=>{q.push({filename:h,Cg:e=>{u--;this.qc();k(e)},xg:e=>{u--;this.qc();c(e)}});this.qc()})}async Te(h,k,c){try{const e=await this.cd(h),l=await n(e);k(l)}catch(e){c(e)}}async Se(){const h=[];for(const [k,c]of Object.entries(this.ha))h.push(this.Re(k,c));await Promise.all(h)}async Re(h,k){if("object"===typeof k)this.ha[h]=new Blob([k.str],{type:k.type}),this.Pb[h]=k.str;else{let c=await this.$e(k);c||(c=this.Ve(k));this.ha[h]=c}}async $e(h){try{return await (await fetch(h)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}Ve(h){h=this.Jf(h);return this.Qe(h.data,h.zg)}Jf(h){var k=h.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var c=h.substring(k+1);k=h.substring(5,k).split(";");h=k[0]||"";const e=k[2];c="base64"===k[1]||"base64"===e?atob(c):decodeURIComponent(c);return{zg:h,data:c}}Qe(h,k){var c=h.length;let e=c>>2,l=new Uint8Array(c),m=new Uint32Array(l.buffer,0,e),p,r;for(r=p=0;p<e;++p)m[p]=h.charCodeAt(r++)|h.charCodeAt(r++)<<8|h.charCodeAt(r++)<<16|h.charCodeAt(r++)<<24;for(c&=
3;c--;)l[r]=h.charCodeAt(r),++r;return new Blob([l],{type:k})}}}"use strict";
{const f=self.Ba;function a(c){return c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(c){return new Promise((e,l)=>{const m=document.createElement("link");m.onload=()=>e(m);m.onerror=p=>l(p);m.rel=
"stylesheet";m.href=c;document.head.appendChild(m)})}function u(c){return new Promise((e,l)=>{const m=new Image;m.onload=()=>e(m);m.onerror=p=>l(p);m.src=c})}async function x(c){c=URL.createObjectURL(c);try{return await u(c)}finally{URL.revokeObjectURL(c)}}function A(c){return new Promise((e,l)=>{let m=new FileReader;m.onload=p=>e(p.target.result);m.onerror=p=>l(p);m.readAsText(c)})}async function w(c,e,l){if(!/firefox/i.test(navigator.userAgent))return await x(c);var m=await A(c);m=(new DOMParser).parseFromString(m,
"image/svg+xml");const p=m.documentElement;if(p.hasAttribute("width")&&p.hasAttribute("height")){const r=p.getAttribute("width"),H=p.getAttribute("height");if(!r.includes("%")&&!H.includes("%"))return await x(c)}p.setAttribute("width",e+"px");p.setAttribute("height",l+"px");m=(new XMLSerializer).serializeToString(m);c=new Blob([m],{type:"image/svg+xml"});return await x(c)}function y(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const C=new Set(["canvas",
"body","html"]);function z(c){C.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function v(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}self.C3_GetSvgImageSize=async function(c){c=await x(c);if(0<c.width&&0<c.height)return[c.width,c.height];{c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const e=c.getBoundingClientRect();document.body.removeChild(c);return[e.width,e.height]}};self.C3_RasterSvgImageBlob=async function(c,
e,l,m,p){c=await w(c,e,l);const r=document.createElement("canvas");r.width=m;r.height=p;r.getContext("2d").drawImage(c,0,0,e,l);return r};let h=!1;document.addEventListener("pause",()=>h=!0);document.addEventListener("resume",()=>h=!1);function k(){try{return window.parent&&window.parent.document.hasFocus()}catch(c){return!1}}f.Pa(class extends self.Qa{constructor(c){super(c,"runtime");this.Ld=!0;this.Ma=-1;this.Wc="any";this.Cd=this.Dd=!1;this.Qc=this.lb=this.wa=null;c.B("canvas","update-size",m=>
this.Hf(m));c.B("runtime","invoke-download",m=>this.uf(m));c.B("runtime","raster-svg-image",m=>this.Bf(m));c.B("runtime","get-svg-image-size",m=>this.sf(m));c.B("runtime","set-target-orientation",m=>this.Ff(m));c.B("runtime","register-sw",()=>this.Cf());c.B("runtime","post-to-debugger",m=>this.xd(m));c.B("runtime","go-to-script",m=>this.xd(m));c.B("runtime","before-start-ticking",()=>this.hf());c.B("runtime","debug-highlight",m=>this.lf(m));c.B("runtime","enable-device-orientation",()=>this.Pe());
c.B("runtime","enable-device-motion",()=>this.Oe());c.B("runtime","add-stylesheet",m=>this.gf(m));c.B("runtime","alert",m=>this.wc(m));c.B("runtime","hide-cordova-splash",()=>this.tf());const e=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",m=>{const p=m.target;e.has(p.tagName.toLowerCase())||y(p)||m.preventDefault()});const l=c.J;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",z);l.addEventListener("selectstart",z);l.addEventListener("gesturehold",
z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),l.addEventListener("pointerdown",z)):l.addEventListener("touchstart",z);this.ib=0;window.addEventListener("mousedown",m=>{1===m.button&&m.preventDefault()});window.addEventListener("mousewheel",v,{passive:!1});window.addEventListener("wheel",v,{passive:!1});window.addEventListener("resize",()=>this.If());c.tb()&&window.addEventListener("focusout",()=>{{const r=
document.activeElement;if(r){var m=r.tagName.toLowerCase();var p=new Set("email number password search tel text url".split(" "));m="textarea"===m?!0:"input"===m?p.has(r.type.toLowerCase()||"text"):y(r)}else m=!1}m||(document.scrollingElement.scrollTop=0)});this.Ha=new Set;this.Qb=new WeakSet;this.la=!1}hf(){"cordova"===this.v.C?(document.addEventListener("pause",()=>this.Dc(!0)),document.addEventListener("resume",()=>this.Dc(!1))):document.addEventListener("visibilitychange",()=>this.Dc(document.hidden));
return{isSuspended:!(!document.hidden&&!h)}}$c(){window.addEventListener("focus",()=>this.Cb("window-focus"));window.addEventListener("blur",()=>{this.Cb("window-blur",{parentHasFocus:k()});this.ib=0});window.addEventListener("fullscreenchange",()=>this.yc());window.addEventListener("webkitfullscreenchange",()=>this.yc());window.addEventListener("mozfullscreenchange",()=>this.yc());window.addEventListener("fullscreenerror",e=>this.zc(e));window.addEventListener("webkitfullscreenerror",e=>this.zc(e));
window.addEventListener("mozfullscreenerror",e=>this.zc(e));window.addEventListener("keydown",e=>this.wd("keydown",e));window.addEventListener("keyup",e=>this.wd("keyup",e));window.addEventListener("dblclick",e=>this.Ac("dblclick",e,d));window.addEventListener("wheel",e=>this.yf(e));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",e=>{this.tc(e);this.Ua("pointerdown",e)}),this.v.pa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.lb=new self.Ee(()=>this.Ye(),
5),this.lb.Gd=!0,window.addEventListener("pointerrawupdate",e=>this.zf(e))):window.addEventListener("pointermove",e=>this.Ua("pointermove",e)),window.addEventListener("pointerup",e=>this.Ua("pointerup",e)),window.addEventListener("pointercancel",e=>this.Ua("pointercancel",e))):(window.addEventListener("mousedown",e=>{this.tc(e);this.Bc("pointerdown",e)}),window.addEventListener("mousemove",e=>this.Bc("pointermove",e)),window.addEventListener("mouseup",e=>this.Bc("pointerup",e)),window.addEventListener("touchstart",
e=>{this.tc(e);this.Ab("pointerdown",e)}),window.addEventListener("touchmove",e=>this.Ab("pointermove",e)),window.addEventListener("touchend",e=>this.Ab("pointerup",e)),window.addEventListener("touchcancel",e=>this.Ab("pointercancel",e)));const c=()=>this.Ec();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0)}Cb(c,e){t(this,c,e||null,n)}ua(){return this.v.ua()}ta(){return this.v.ta()}If(){const c=
this.ua(),e=this.ta();this.Cb("window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio});this.v.tb()&&(-1!==this.Ma&&clearTimeout(this.Ma),this.yd(c,e,0))}Qf(c,e,l){-1!==this.Ma&&clearTimeout(this.Ma);this.Ma=setTimeout(()=>this.yd(c,e,l),48)}yd(c,e,l){const m=this.ua(),p=this.ta();this.Ma=-1;m!=c||p!=e?this.Cb("window-resize",{innerWidth:m,innerHeight:p,devicePixelRatio:window.devicePixelRatio}):10>l&&this.Qf(m,p,l+1)}Ff(c){this.Wc=c.targetOrientation}ig(){const c=this.Wc;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(e=>console.warn("[Construct 3] Failed to lock orientation: ",e));else try{let e=!1;screen.lockOrientation?e=screen.lockOrientation(c):screen.webkitLockOrientation?e=screen.webkitLockOrientation(c):screen.mozLockOrientation?e=screen.mozLockOrientation(c):screen.msLockOrientation&&(e=screen.msLockOrientation(c));e||console.warn("[Construct 3] Failed to lock orientation")}catch(e){console.warn("[Construct 3] Failed to lock orientation: ",
e)}}yc(){const c=f.hc();c&&"any"!==this.Wc&&this.ig();t(this,"fullscreenchange",{isFullscreen:c,innerWidth:this.ua(),innerHeight:this.ta()})}zc(c){console.warn("[Construct 3] Fullscreen request failed: ",c);t(this,"fullscreenerror",{isFullscreen:f.hc(),innerWidth:this.ua(),innerHeight:this.ta()})}Dc(c){c?this.v.pc():this.v.Fc();t(this,"visibilitychange",{hidden:c})}wd(c,e){"Backspace"===e.key&&z(e);const l=b.get(e.code)||e.code;B(this,c,{code:l,key:e.key,which:e.which,repeat:e.repeat,altKey:e.altKey,
ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,timeStamp:e.timeStamp},d)}yf(c){t(this,"wheel",{clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,deltaX:c.deltaX,deltaY:c.deltaY,deltaZ:c.deltaZ,deltaMode:c.deltaMode,timeStamp:c.timeStamp},d)}Ac(c,e,l){a(e)||B(this,c,{button:e.button,buttons:e.buttons,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,timeStamp:e.timeStamp},l)}Bc(c,e){if(!a(e)){var l=this.ib;"pointerdown"===c&&0!==l?c="pointermove":"pointerup"===
c&&0!==e.buttons&&(c="pointermove");B(this,c,{pointerId:1,pointerType:"mouse",button:e.button,buttons:e.buttons,lastButtons:l,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:e.timeStamp},d);this.ib=e.buttons;this.Ac(e.type,e,g)}}Ua(c,e){if(this.lb&&"pointermove"!==c){var l=this.lb;l.ab||(G(l),l.Nb=Date.now())}l=0;"mouse"===e.pointerType&&(l=this.ib);B(this,c,{pointerId:e.pointerId,pointerType:e.pointerType,
button:e.button,buttons:e.buttons,lastButtons:l,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:e.width||0,height:e.height||0,pressure:e.pressure||0,tangentialPressure:e.tangentialPressure||0,tiltX:e.tiltX||0,tiltY:e.tiltY||0,twist:e.twist||0,timeStamp:e.timeStamp},d);"mouse"===e.pointerType&&(l="mousemove","pointerdown"===c?l="mousedown":"pointerup"===c&&(l="pointerup"),this.Ac(l,e,g),this.ib=e.buttons)}zf(c){this.Qc=c;c=this.lb;if(-1===c.Na){var e=Date.now(),l=e-c.Nb,m=c.og;
l>=m&&c.Gd?(c.Nb=e,c.ab=!0,c.Hc(),c.ab=!1):c.Na=self.setTimeout(c.Xd,Math.max(m-l,4))}}Ye(){this.Ua("pointermove",this.Qc);this.Qc=null}Ab(c,e){for(let l=0,m=e.changedTouches.length;l<m;++l){const p=e.changedTouches[l];B(this,c,{pointerId:p.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:p.clientX,clientY:p.clientY,pageX:p.pageX,pageY:p.pageY,width:2*(p.radiusX||p.webkitRadiusX||0),height:2*(p.radiusY||p.webkitRadiusY||0),pressure:p.force||p.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:p.rotationAngle||0,timeStamp:e.timeStamp},d)}}tc(c){window!==window.top&&window.focus();this.ud(c.target)&&document.activeElement&&!this.ud(document.activeElement)&&document.activeElement.blur()}ud(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}Pe(){this.Dd||(this.Dd=!0,window.addEventListener("deviceorientation",c=>this.nf(c)),window.addEventListener("deviceorientationabsolute",c=>this.pf(c)))}Oe(){this.Cd||(this.Cd=!0,window.addEventListener("devicemotion",
c=>this.mf(c)))}nf(c){t(this,"deviceorientation",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp,webkitCompassHeading:c.webkitCompassHeading,webkitCompassAccuracy:c.webkitCompassAccuracy},d)}pf(c){t(this,"deviceorientationabsolute",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp},d)}mf(c){let e=null;var l=c.acceleration;l&&(e={x:l.x||0,y:l.y||0,z:l.z||0});l=null;var m=c.accelerationIncludingGravity;m&&(l={x:m.x||
0,y:m.y||0,z:m.z||0});m=null;const p=c.rotationRate;p&&(m={alpha:p.alpha||0,beta:p.beta||0,gamma:p.gamma||0});t(this,"devicemotion",{acceleration:e,accelerationIncludingGravity:l,rotationRate:m,interval:c.interval,timeStamp:c.timeStamp},d)}Hf(c){const e=this.v,l=e.J;l.style.width=c.styleWidth+"px";l.style.height=c.styleHeight+"px";l.style.marginLeft=c.marginLeft+"px";l.style.marginTop=c.marginTop+"px";e.jd();this.Ld&&(l.style.display="",this.Ld=!1)}uf(c){const e=c.url;c=c.filename;const l=document.createElement("a"),
m=document.body;l.textContent=c;l.href=e;l.download=c;m.appendChild(l);l.click();m.removeChild(l)}async Bf(c){var e=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);e=e?await createImageBitmap(c,e):await createImageBitmap(c);return{imageBitmap:e,transferables:[e]}}async sf(c){return await self.C3_GetSvgImageSize(c.blob)}async gf(c){await q(c.url)}Ec(){var c=[...this.Ha];this.Ha.clear();if(!this.la)for(const e of c)(c=e.play())&&
c.catch(()=>{this.Qb.has(e)||this.Ha.add(e)})}sa(c){if("function"!==typeof c.play)throw Error("missing play function");this.Qb.delete(c);let e;try{e=c.play()}catch(l){this.Ha.add(c);return}e&&e.catch(()=>{this.Qb.has(c)||this.Ha.add(c)})}Aa(c){this.Ha.delete(c);this.Qb.add(c)}wb(c){this.la=!!c}tf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}lf(c){if(c.show){this.wa||(this.wa=document.createElement("div"),this.wa.id="inspectOutline",document.body.appendChild(this.wa));
var e=this.wa;e.style.display="";e.style.left=c.left-1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.wa&&(this.wa.style.display="none")}Cf(){window.C3_RegisterSW&&window.C3_RegisterSW()}xd(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}ef(c,e){return this.v.kd(this.Wa,"js-invoke-function",{name:c,params:e},void 0,void 0)}wc(c){alert(c.message)}})}"use strict";
async function L(f){if(f.ng)throw Error("already initialised");f.ng=!0;var a=f.Ub.sc("dispatchworker.js");f.Jc=await f.Ub.ac(a,f.K,{name:"DispatchWorker"});a=new MessageChannel;f.Nc=a.port1;f.Jc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.Uc=await N(f)}function M(f){return[f.Nc,f.Uc]}
async function N(f){const a=f.Md.length;var b=f.Ub.sc("jobworker.js");b=await f.Ub.ac(b,f.K,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Jc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.Md.push(b);return g.port1}
self.Ae=class{constructor(f){this.Ub=f;this.K=f.K;this.K="preview"===f.C?this.K+"c3/workers/":this.K+f.Vb;this.qg=Math.min(navigator.hardwareConcurrency||2,16);this.Jc=null;this.Md=[];this.Uc=this.Nc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ba({Dg:!1,Eg:"workermain.js",Oa:["scripts/c3runtime.js"],Ag:"scripts/",Zc:[],Yd:"html5"}));"use strict";
self.Ba.Pa(class extends self.Qa{constructor(f){super(f,"mouse");D(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
{function f(a){a.stopPropagation()}self.Ba.Pa(class extends self.qe{constructor(a){super(a,"progress-bar")}dd(a,b){const d=document.createElement("progress");d.style.position="absolute";d.style.userSelect="none";d.style.webkitUserSelect="none";d.addEventListener("touchstart",f);d.addEventListener("touchmove",f);d.addEventListener("touchend",f);d.addEventListener("mousedown",f);d.addEventListener("mouseup",f);d.addEventListener("click",()=>{var g;g||(g={});g.elementId=a;B(this,"click",g)});b.id&&(d.id=
b.id);this.oc(d,b);return d}oc(a,b){a.title=b.title;const d=b.value;b=b.max;0<b&&0<=d?(a.max=b,a.value=d):(a.removeAttribute("value"),a.removeAttribute("max"))}})}"use strict";function O(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>t(f,"sw-message",a.data))}
function P(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.Ba.Pa(class extends self.Qa{constructor(f){super(f,"browser");this.C="";E(this,[["get-initial-state",a=>{this.C=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>O(this)],
["alert",a=>this.wc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Cc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>P(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var d=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a?window.open(b,"_blank"):this.Ig||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,d=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,d))}],["request-fullscreen",
a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{t(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;t(this,"backbutton")})}wc(f){alert(f.message)}Cc(f){f=f.isFocus;if("nwjs"===this.C){const a="nwjs"===this.C?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});"use strict";
{const f=180/Math.PI;self.da=class extends self.Qa{constructor(a){super(a,"audio");this.Jb=this.f=null;this.Lb=this.Mc=!1;this.oa=()=>this.jg();this.ba=[];this.D=[];this.ga=null;this.Nd="";this.Od=-1;this.kb=new Map;this.Rc=1;this.la=!1;this.Xc=0;this.Xb=1;this.Kc=0;this.Qd="HRTF";this.Hd="inverse";this.Rd=600;this.Pd=1E4;this.Td=1;this.Jd=this.Vc=!1;this.ug=this.v.ye();this.ca=new Map;this.Ea=new Set;this.Oc=!1;this.Sc="";this.xa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.xf(b,d);this.Ib=null;
self.C3Audio_GetOutputStream=()=>this.rf();self.C3Audio_DOMInterface=this;E(this,[["create-audio-context",b=>this.Ue(b)],["play",b=>this.Kf(b)],["stop",b=>this.gg(b)],["stop-all",()=>this.hg()],["set-paused",b=>this.$f(b)],["set-volume",b=>this.eg(b)],["fade-volume",b=>this.Ze(b)],["set-master-volume",b=>this.Yf(b)],["set-muted",b=>this.Zf(b)],["set-silent",b=>this.bg(b)],["set-looping",b=>this.Xf(b)],["set-playback-rate",b=>this.ag(b)],["seek",b=>this.Rf(b)],["preload",b=>this.Lf(b)],["unload",b=>
this.kg(b)],["unload-all",()=>this.lg()],["set-suspended",b=>this.cg(b)],["add-effect",b=>this.pd(b)],["set-effect-param",b=>this.Uf(b)],["remove-effects",b=>this.Nf(b)],["tick",b=>this.Gf(b)],["load-state",b=>this.vf(b)]])}async Ue(a){a.isiOSCordova&&(this.Vc=!0);this.Xc=a.timeScaleMode;this.Qd=["equalpower","HRTF","soundfield"][a.panningModel];this.Hd=["linear","inverse","exponential"][a.distanceModel];this.Rd=a.refDistance;this.Pd=a.maxDistance;this.Td=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.qd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.qd()};this.Jb=this.f.createGain();this.Jb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.bc();try{await Promise.all(a.preloadList.map(d=>
this.yb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}qd(){this.Lb||(this.Mc=!1,window.addEventListener("pointerup",this.oa,!0),window.addEventListener("touchend",this.oa,!0),window.addEventListener("click",this.oa,!0),window.addEventListener("keydown",this.oa,!0),this.Lb=!0)}We(){this.Lb&&(this.Mc=!0,window.removeEventListener("pointerup",this.oa,!0),window.removeEventListener("touchend",this.oa,!0),window.removeEventListener("click",
this.oa,!0),window.removeEventListener("keydown",this.oa,!0),this.Lb=!1)}jg(){if(!this.Mc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.We()}}W(){return this.f}bc(){return this.f.currentTime}qa(){return this.Jb}fd(a){return(a=this.ca.get(a.toLowerCase()))?a[0].P():this.qa()}$d(a,b){a=a.toLowerCase();let d=this.ca.get(a);d||(d=[],this.ca.set(a,d));b.Wf(d.length);
b.dg(a);d.push(b);this.Ad(a)}Ad(a){let b=this.qa();const d=this.ca.get(a);if(d&&d.length){b=d[0].P();for(let g=0,n=d.length;g<n;++g){const q=d[g];g+1===n?q.S(this.qa()):q.S(d[g+1].P())}}for(const g of this.ja(a))g.Fe(b);this.xa&&this.Sc===a&&(this.xa.disconnect(),this.xa.connect(b))}rb(){return this.Rc}sb(){return this.la}Vf(){this.Jd=!0}se(a,b){return b?this.v.mg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):new Promise((d,g)=>{this.f.decodeAudioData(a,
d,g)})}sa(a){this.v.sa(a)}Aa(a){this.v.Aa(a)}ld(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.c():++b}this.D.length=b}Ge(){let a=0;for(let b=0,d=this.ba.length;b<d;++b){const g=this.ba[b];this.ba[a]=g;g.ra()?g.c():++a}this.ba.length=a}*ja(a){if(a)for(const b of this.D)self.da.te(b.$,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async yb(a,b,d,g,n){for(const q of this.ba)if(q.Sa()===b)return await Q(q),q;if(n)return null;g&&(this.Vc||this.Jd)&&
this.Ge();n="audio/webm; codecs=opus"===d&&!this.ug;g&&n&&this.Vf();a=!g||this.Vc||n?new self.ne(this,a,b,d,g,n):new self.le(this,a,b,d,g);this.ba.push(a);await Q(a);return a}async rc(a,b,d,g,n){for(const q of this.D)if(q.Sa()===b&&(q.Zb()||n))return q.Ie(g),q;a=await this.yb(a,b,d,n);g="html5"===a.Gc?new self.me(a.i,a,g):new self.oe(a.i,a,g);this.D.push(g);return g}Me(a){let b=this.kb.get(a);if(!b){let d=null;b={Yc:0,promise:new Promise(g=>d=g),resolve:d};this.kb.set(a,b)}b.Yc++}Of(a){const b=this.kb.get(a);
if(!b)throw Error("expected pending tag");b.Yc--;0===b.Yc&&(b.resolve(),this.kb.delete(a))}nc(a){a||(a=this.Nd);return(a=this.kb.get(a))?a.promise:Promise.resolve()}zb(){if(0<this.Ea.size)F(this);else for(const a of this.D)if(a.gd()){F(this);break}}Ca(){for(var a of this.Ea)a.Ca();a=this.bc();for(var b of this.D)b.Ca(a);b=this.D.filter(d=>d.gd()).map(d=>d.Ra());t(this,"state",{tickCount:this.Od,audioInstances:b,analysers:[...this.Ea].map(d=>d.ve())});0===b.length&&0===this.Ea.size&&this.Mb&&(this.v.Pf(this.Wd),
this.Mb=!1)}jc(a,b,d){t(this,"trigger",{type:a,tag:b,aiid:d})}async Kf(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,q=a.tag,u=a.isLooping,x=a.vol,A=a.pos,w=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.Nd=q;this.Me(q);try{this.ga=await this.rc(b,d,g,q,n),w?(this.ga.vb(!0),this.ga.He(w.x,w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&
this.ga.Je(w.uid)):this.ga.vb(!1),this.ga.Play(u,x,A,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Of(q)}F(this)}gg(a){a=a.tag;for(const b of this.ja(a))b.ka()}hg(){for(const a of this.D)a.ka()}$f(a){const b=a.tag;a=a.paused;for(const d of this.ja(b))a?d.Ta():d.ub();this.zb()}eg(a){const b=a.tag;a=a.vol;for(const d of this.ja(b))d.xb(a)}async Ze(a){const b=a.tag,d=a.vol,g=a.duration;a=a.stopOnEnd;await this.nc(b);for(const n of this.ja(b))n.ue(d,
g,a);this.zb()}Yf(a){this.Rc=a.vol;for(const b of this.D)b.Fb()}Zf(a){const b=a.tag;a=a.isMuted;for(const d of this.ja(b))d.md(a)}bg(a){this.la=a.isSilent;this.v.wb(this.la);for(const b of this.D)b.Eb()}Xf(a){const b=a.tag;a=a.isLooping;for(const d of this.ja(b))d.lc(a)}async ag(a){const b=a.tag;a=a.rate;await this.nc(b);for(const d of this.ja(b))d.od(a)}async Rf(a){const b=a.tag;a=a.pos;await this.nc(b);for(const d of this.ja(b))d.kc(a)}async Lf(a){const b=a.originalUrl,d=a.url,g=a.type;a=a.isMusic;
try{await this.rc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async kg(a){if(a=await this.yb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}lg(){for(const a of this.ba)a.c();this.ba.length=0}cg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.mc(a);a&&this.f.suspend&&this.f.suspend()}Gf(a){this.Xb=a.timeScale;this.Kc=a.gameTime;this.Od=a.tickCount;if(0!==this.Xc)for(var b of this.D)b.Da();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.fa===a&&g.nd(d.x,d.y,d.angle)}}async pd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.fe(this,...g);else if("delay"===b)g=new self.de(this,...g);else if("convolution"===b){b=null;try{b=await this.yb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",n);return}g=new self.ce(this,b.aa,...g);g.Sf(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)g=new self.ge(this,...g);else if("phaser"===b)g=new self.ie(this,...g);else if("gain"===b)g=new self.he(this,...g);else if("tremolo"===b)g=new self.ke(this,...g);else if("ringmod"===b)g=new self.je(this,...g);else if("distortion"===b)g=new self.ee(this,...g);else if("compressor"===b)g=new self.be(this,...g);else if("analyser"===b)g=new self.ae(this,...g);else throw Error("invalid effect type");this.$d(d,g);this.zd()}Uf(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,
q=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,q),this.zd())}Nf(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const d of b)d.c();this.ca.delete(a);this.Ad(a)}}Le(a){this.Ea.add(a);this.zb()}Mf(a){this.Ea.delete(a)}zd(){this.Oc||(this.Oc=!0,Promise.resolve().then(()=>this.Xe()))}Xe(){const a={};for(const [b,d]of this.ca)a[b]=d.map(g=>g.Ra());t(this,"fxstate",{fxstate:a});this.Oc=!1}async vf(a){const b=a.saveLoadMode;if(3!==b)for(var d of this.D)d.ra()&&1===
b||(d.ra()||2!==b)&&d.ka();for(const g of this.ca.values())for(const n of g)n.c();this.ca.clear();this.Xb=a.timeScale;this.Kc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.la=a.isSilent;this.v.wb(this.la);this.Rc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.pd(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.ff(g,b)));this.zb()}async ff(a,b){if(3!==b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,
q=a.isMusic,u=a.tag,x=a.isLooping,A=a.volume,w=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.rc(d,g,n,u,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.De(a.pan);b.Play(x,A,w,0);a.isPlaying||b.Ta();b.vc(a)}}}xf(a,b){this.xa&&this.xa.disconnect();this.Sc=b.toLowerCase();this.xa=this.f.createMediaStreamSource(a);this.xa.connect(this.fd(this.Sc))}rf(){this.Ib||(this.Ib=this.f.createMediaStreamDestination(),this.Jb.connect(this.Ib));return this.Ib.stream}static te(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ke(a){return a*f}static re(a){return Math.pow(10,a/20)}static ed(a){return Math.max(Math.min(self.da.re(a),1),0)}static Ce(a){return Math.log(a)/Math.log(10)*20}static Be(a){return self.da.Ce(Math.max(Math.min(a,1),0))}static wg(a,b){return 1-Math.exp(-b*a)}};self.Ba.Pa(self.da)}"use strict";function Q(f){f.Ob||(f.Ob=f.uc());return f.Ob}
self.ad=class{constructor(f,a,b,d,g){this.i=f;this.sg=a;this.ya=b;this.R=d;this.pg=g;this.Gc="";this.Ob=null}c(){this.Ob=this.i=null}uc(){}W(){return this.i.W()}dc(){return this.sg}Sa(){return this.ya}cc(){return this.R}ra(){return this.pg}ea(){}};"use strict";
self.le=class extends self.ad{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Gc="html5";this.I=new Audio;this.I.crossOrigin="anonymous";this.I.autoplay=!1;this.I.preload="auto";this.eb=this.fb=null;this.I.addEventListener("canplaythrough",()=>!0);this.jb=this.W().createGain();this.hb=null;this.I.addEventListener("canplay",()=>{this.fb&&(this.fb(),this.eb=this.fb=null);!this.hb&&this.I&&(this.hb=this.W().createMediaElementSource(this.I),this.hb.connect(this.jb))});this.onended=null;this.I.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.I.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.ya}' error: `,n);this.eb&&(this.eb(n),this.eb=this.fb=null)})}c(){this.i.ld(this);this.jb.disconnect();this.jb=null;this.hb.disconnect();this.hb=null;this.I&&!this.I.paused&&this.I.pause();this.I=this.onended=null;super.c()}uc(){return new Promise((f,a)=>{this.fb=f;this.eb=a;this.I.src=this.ya})}O(){return this.I}ea(){return this.I.duration}};"use strict";
async function R(f){if(f.va)return f.va;var a=f.i.v;if("cordova"===a.C&&a.ze(f.ya)&&"file:"===location.protocol)f.va=await a.$b(f.ya);else{a=await fetch(f.ya);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.va=await a.arrayBuffer()}}async function S(f){if(f.aa)return f.aa;f.aa=await f.i.se(f.va,f.rg);f.va=null}
self.ne=class extends self.ad{constructor(f,a,b,d,g,n){super(f,a,b,d,g);this.Gc="webaudio";this.aa=this.va=null;this.rg=!!n}c(){this.i.ld(this);this.aa=this.va=null;super.c()}async uc(){try{await R(this),await S(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.ya}': `,f)}}ea(){return this.aa?this.aa.duration:0}};"use strict";
{let f=0;self.bd=class{constructor(a,b,d){this.i=a;this.L=b;this.$=d;this.Gb=f++;this.M=this.W().createGain();this.M.connect(this.qa());this.A=null;this.bb=!1;this.G=!0;this.V=this.ia=this.F=!1;this.nb=1;this.Fa=!1;this.Z=1;a=this.i.Xc;this.Pc=1===a&&!this.ra()||2===a;this.Za=this.fa=-1;this.Vd=!1}c(){this.L=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}qa(){return this.i.fd(this.$)}rb(){return this.i.rb()}qb(){return this.Pc?this.i.Kc:
performance.now()/1E3}dc(){return this.L.dc()}Sa(){return this.L.Sa()}cc(){return this.L.cc()}ra(){return this.L.ra()}Ie(a){this.$=a}T(){}Zb(){}IsPlaying(){return!this.G&&!this.F&&!this.T()}gd(){return!this.G&&!this.T()}za(){}ea(){return this.L.ea()}Play(){}ka(){}Ta(){}ub(){}xb(a){this.nb=a;this.M.gain.cancelScheduledValues(0);this.Za=-1;this.M.gain.value=this.ec()}ue(a,b,d){if(!this.Fa){a*=this.rb();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.bc();b=n+b;g.setValueAtTime(g.value,n);
g.linearRampToValueAtTime(a,b);this.nb=a;this.Za=b;this.Vd=d}}Fb(){this.xb(this.nb)}Ca(a){-1!==this.Za&&a>=this.Za&&(this.Za=-1,this.Vd&&this.ka(),this.i.jc("fade-ended",this.$,this.Gb))}ec(){const a=this.nb*this.rb();return isFinite(a)?a:0}md(a){a=!!a;this.Fa!==a&&(this.Fa=a,this.Eb())}sb(){return this.i.sb()}Eb(){}lc(){}od(a){this.Z!==a&&(this.Z=a,this.Da())}Da(){}kc(){}mc(){}vb(a){a=!!a;this.bb!==a&&((this.bb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Qd,this.A.distanceModel=
this.i.Hd,this.A.refDistance=this.i.Rd,this.A.maxDistance=this.i.Pd,this.A.rolloffFactor=this.i.Td),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.qa())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.qa())))}He(a,b,d,g,n,q){this.bb&&(this.nd(a,b,d),a=self.da.Ke,this.A.coneInnerAngle=a(g),this.A.coneOuterAngle=a(n),this.A.coneOuterGain=q)}nd(a,b,d){this.bb&&(this.A.setPosition(a,b,0),this.A.setOrientation(Math.cos(d),Math.sin(d),0))}Je(a){this.fa=a}fc(){}Fe(a){const b=
this.A||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Gb,tag:this.$,duration:this.ea(),volume:this.nb,isPlaying:this.IsPlaying(),playbackTime:this.za(),playbackRate:this.Z,uid:this.fa,bufferOriginalUrl:this.dc(),bufferUrl:"",bufferType:this.cc(),isMusic:this.ra(),isLooping:this.V,isMuted:this.Fa,resumePosition:this.fc(),pan:this.we()}}vc(a){this.od(a.playbackRate);this.md(a.isMuted)}we(){if(!this.A)return null;const a=this.A;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}De(a){a?(this.vb(!0),a=this.A,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.vb(!1)}}}"use strict";
self.me=class extends self.bd{constructor(f,a,b){super(f,a,b);this.L.jb.connect(this.M);this.L.onended=()=>this.xc()}c(){this.ka();this.L.jb.disconnect();super.c()}O(){return this.L.O()}xc(){this.G=!0;this.fa=-1;this.i.jc("ended",this.$,this.Gb)}T(){return this.O().ended}Zb(){return this.G?!0:this.T()}za(f){let a=this.O().currentTime;f&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.xb(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,g)}this.i.sa(d);this.F=this.G=!1;this.V=f;this.Z=1}ka(){const f=this.O();f.paused||f.pause();this.i.Aa(f);this.G=!0;this.F=!1;this.fa=-1}Ta(){if(!(this.F||this.G||this.T())){var f=this.O();f.paused||f.pause();this.i.Aa(f);this.F=!0}}ub(){!this.F||this.G||this.T()||(this.i.sa(this.O()),this.F=!1)}Eb(){this.O().muted=this.Fa||this.sb()}lc(f){f=!!f;
this.V!==f&&(this.V=f,this.O().loop=f)}Da(){let f=this.Z;this.Pc&&(f*=this.i.Xb);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}kc(f){if(!this.G&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}fc(){return this.za()}mc(f){f?this.IsPlaying()?(this.O().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.sa(this.O()),this.ia=!1)}};"use strict";
function T(f){f.j&&f.j.disconnect();f.j=null;f.Va=null}
self.oe=class extends self.bd{constructor(f,a,b){super(f,a,b);this.j=null;this.Rb=d=>this.xc(d);this.Lc=!0;this.Va=null;this.N=this.Wb=0;this.Tc=1}c(){this.ka();T(this);this.Rb=null;super.c()}xc(f){this.F||this.ia||f.target!==this.Va||(this.G=this.Lc=!0,this.fa=-1,T(this),this.i.jc("ended",this.$,this.Gb))}T(){return!this.G&&this.j&&this.j.loop||this.F?!1:this.Lc}Zb(){return!this.j||this.G?!0:this.T()}za(f){let a;a=this.F?this.N:this.qb()-this.Wb;f&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(f,
a,b,d){this.Tc=1;this.xb(a);T(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.aa;this.j.connect(this.M);this.Va=this.j;this.j.onended=this.Rb;this.j.loop=f;this.j.start(d,b);this.F=this.G=this.Lc=!1;this.V=f;this.Z=1;this.Wb=this.qb()-b}ka(){if(this.j)try{this.j.stop(0)}catch(f){}this.G=!0;this.F=!1;this.fa=-1}Ta(){this.F||this.G||this.T()||(this.N=this.za(!0),this.V&&(this.N%=this.ea()),this.F=!0,this.j.stop(0))}ub(){!this.F||this.G||this.T()||(T(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.aa,this.j.connect(this.M),this.Va=this.j,this.j.onended=this.Rb,this.j.loop=this.V,this.Fb(),this.Da(),this.Wb=this.qb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.F=!1)}ec(){return super.ec()*this.Tc}Eb(){this.Tc=this.Fa||this.sb()?0:1;this.Fb()}lc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Da(){let f=this.Z;this.Pc&&(f*=this.i.Xb);this.j&&(this.j.playbackRate.value=f)}kc(f){this.G||this.T()||(this.F?this.N=f:(this.Ta(),this.N=f,this.ub()))}fc(){return this.N}mc(f){f?
this.IsPlaying()?(this.ia=!0,this.N=this.za(!0),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(T(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.aa,this.j.connect(this.M),this.Va=this.j,this.j.onended=this.Rb,this.j.loop=this.V,this.Fb(),this.Da(),this.Wb=this.qb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.ia=!1)}vc(f){super.vc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Kd=-1;this.R=this.$="";this.g=null}c(){this.f=null}Wf(a){this.Kd=a}dg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.f.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Ra(){return{type:this.R,tag:this.$,params:this.g}}}
self.fe=class extends f{constructor(a,b,d,g,n,q,u){super(a);this.R="filter";this.g=[b,d,g,n,q,u];this.l=this.o();this.b=this.o();this.b.gain.value=u;this.a=this.o();this.a.gain.value=1-u;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=g;this.u.Q.value=n;this.u.gain.vlaue=q;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,g)}}};self.de=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.gb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.Ya=this.o();this.Ya.gain.value=d;this.l.connect(this.gb);this.l.connect(this.a);this.gb.connect(this.b);this.gb.connect(this.U);this.U.connect(this.Ya);this.Ya.connect(this.gb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.gb.disconnect();this.U.disconnect();this.Ya.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const n=self.da.ed;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.Ya.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.ce=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Fd=this.Ed="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.Xa=this.f.createConvolver();this.Xa.normalize=d;this.Xa.buffer=b;this.l.connect(this.Xa);this.l.connect(this.a);this.Xa.connect(this.b)}c(){this.l.disconnect();this.Xa.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}Sf(a,b){this.Ed=a;this.Fd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Ed;a.bufferUrl="";a.bufferType=this.Fd;return a}};self.ge=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="flanger";this.g=[b,d,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.$a=this.o();this.$a.gain.value=n;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.H=this.o();this.H.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.$a);this.$a.connect(this.U);this.s.connect(this.H);this.H.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.H.disconnect();this.a.disconnect();this.b.disconnect();this.$a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.H.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.$a.gain,b/100,d,g)}}};self.ie=class extends f{constructor(a,b,d,g,n,q,u){super(a);this.R="phaser";this.g=[b,d,g,n,q,u];this.l=this.o();this.a=this.o();this.a.gain.value=1-u/2;this.b=this.o();this.b.gain.value=u/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=q;this.H=this.o();this.H.gain.value=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.H);this.H.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.H.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.H.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,g)}}};self.he=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const n=self.da.ed;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.ke=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.H=this.o();this.H.gain.value=d/2;this.s.connect(this.H);this.H.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.H.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,d,g);this.m(this.H.gain.value,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.je=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.mb=this.o();
this.mb.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.mb.gain);this.s.start(0);this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.mb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,d,g);this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ee=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="distortion";this.g=[b,d,g,n,q];this.l=this.o();this.Tb=this.o();this.Sb=this.o();this.Tf(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.Yb=this.f.createWaveShaper();this.Ic=new Float32Array(65536);this.af(b,d);this.Yb.curve=this.Ic;this.l.connect(this.Tb);this.l.connect(this.a);this.Tb.connect(this.Yb);
this.Yb.connect(this.Sb);this.Sb.connect(this.b)}c(){this.l.disconnect();this.Tb.disconnect();this.Yb.disconnect();this.Sb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Tf(a,b){.01>a&&(a=.01);this.Tb.gain.value=a;this.Sb.gain.value=Math.pow(1/a,.6)*b}af(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.fg(g,a,b);this.Ic[32768+d]=g;this.Ic[32768-d-1]=-g}}fg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.wg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.be=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="compressor";this.g=[b,d,g,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ae=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Id=new Float32Array(this.h.frequencyBinCount);this.Ud=new Uint8Array(b);this.Sd=this.Ia=0;this.i.Le(this)}c(){this.i.Mf(this);this.h.disconnect();super.c()}Ca(){this.h.getFloatFrequencyData(this.Id);this.h.getByteTimeDomainData(this.Ud);const a=this.h.fftSize;let b=this.Ia=0;for(var d=0;d<a;++d){let g=(this.Ud[d]-128)/128;0>g&&(g=-g);
this.Ia<g&&(this.Ia=g);b+=g*g}d=self.da.Be;this.Ia=d(this.Ia);this.Sd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}ve(){return{tag:this.$,index:this.Kd,peak:this.Ia,rms:this.Sd,binCount:this.h.frequencyBinCount,freqBins:this.Id}}}};